name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imagee
      
    - name: Push into Docker Hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        IMAGE_NAME: "imagee"
      run: |
       docker tag $IMAGE_NAME $DOCKER_USERNAME/wec1
       docker push $DOCKER_USERNAME/wec1
