name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imagee

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        IMAGE_NAME: "imagee"
      run: |
       docker tag $IMAGE_NAME $DOCKER_USERNAME/wec1
       docker push $DOCKER_USERNAME/wec1
